test:
  container_name: scws_test
  image: scws:0.0.2
  command: "npm test"

  working_dir: /app
  volumes:
    - ./:/app
  ports:
    - "3001:3001"
    - "1337:1337"

dev:
  container_name: scws_dev
  image: scws:0.0.2
  command: "npm run dev"

  working_dir: /app
  volumes:
    - ./:/app
  ports:
    - "1337:1337"

prod:
  container_name: scws_prod
  image: scws:0.0.2
  command: "npm start"

  working_dir: /app
  volumes:
    - ./:/app
  ports:
    - "1337:80"
